[package]
name = "n-body-2"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11"
glam = "0.30" # math
log = "0.4"
pollster = "0.4"
sdl3 = {version = "0.15", features = ["raw-window-handle"]}
wgpu = "26.0"
